exclude: |
  (?x)
  ^template/
default_language_version:
  python: python3
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
