# Config file .travis.yml

language: python

python:
    - "2.7"

before_install:
    - pip install --upgrade pip

install:
    - pip install coveralls flake8
    - pip install -r requirements.txt

script:
    - python setup.py flake8
    - coverage run setup.py test
    - python setup.py install

after_success:
  coveralls
