====================
addon one maintainer
====================

.. 
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   !! This file is generated by oca-gen-addon-readme !!
   !! changes will be overwritten.                   !!
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   !! source digest: sha256:15ae25bf0bec4b45e93e38fb03caceac901d14dfdf33683a9d6c4fc1d8e4be8c
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

.. |badge1| image:: https://img.shields.io/badge/maturity-Beta-yellow.png
    :target: https://odoo-community.org/page/development-status
    :alt: Beta
.. |badge2| image:: https://img.shields.io/badge/github-acme%2Fserver--tools-lightgray.png?logo=github
    :target: https://github.com/acme/server-tools/tree/12.0/addon_two_maintainers
    :alt: acme/server-tools

|badge1| |badge2|

Some description

* blah
* blabla

**Table of contents**

.. contents::
   :local:

Bug Tracker
===========

Bugs are tracked on `GitHub Issues <https://github.com/acme/server-tools/issues>`_.
In case of trouble, please check there if your issue has already been reported.
If you spotted it first, help us to smash it by providing a detailed and welcomed
`feedback <https://github.com/acme/server-tools/issues/new?body=module:%20addon_two_maintainers%0Aversion:%2012.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.

Do not contact contributors directly about support or help with technical issues.

Credits
=======

Authors
~~~~~~~

* Acme Inc

Maintainers
~~~~~~~~~~~

.. |maintainer-toto| image:: https://github.com/toto.png?size=40px
    :target: https://github.com/toto
    :alt: toto
.. |maintainer-titi| image:: https://github.com/titi.png?size=40px
    :target: https://github.com/titi
    :alt: titi

Current maintainers:

|maintainer-toto| |maintainer-titi| 

This module is part of the `acme/server-tools <https://github.com/acme/server-tools/tree/12.0/addon_two_maintainers>`_ project on GitHub.

You are welcome to contribute.
