#!/usr/bin/env python
import subprocess

from oca_projects import OCA_REPOSITORY_NAMES, url


def main():
    for project in OCA_REPOSITORY_NAMES:
        cmd = ['git', 'clone', url(project), project]
        subprocess.call(cmd)


if __name__ == '__main__':
    main()
