#!/usr/bin/env python
""" Make a pypi compatible simple index from a wheelhouse directory

A trivial wheelhouse, used with pip --find-links has scalability issues.
A simple index, used with pip --extra-index-url scales much better.

The index has the following structure: ./pkg-name/pkg_name-x.y.z.whl.

The index generated by this script is made of symbolic links to the
source wheelhouse.
"""
import argparse
import os


def wheelname(filename):
    return filename.split('-')[0].replace('_', '-')


def main():
    parser = argparse.ArgumentParser(
        description="Make a simple index from a wheelhouse directory")
    parser.add_argument("-s", "--source-dir", required=True)
    parser.add_argument("-t", "--target-dir", required=True)
    args = parser.parse_args()

    for filename in os.listdir(args.source_dir):
        filepath = os.path.join(args.source_dir, filename)
        if not os.path.isfile(filepath):
            continue
        if not filename.endswith('.whl'):
            continue
        pkgname = wheelname(filename)
        assert not pkgname.endswith('.whl')
        pkgdirpath = os.path.join(args.target_dir, pkgname)
        if not os.path.isdir(pkgdirpath):
            os.mkdir(pkgdirpath)
        pkgpath = os.path.join(pkgdirpath, filename)
        if not os.path.islink(pkgpath):
            source = os.path.relpath(os.path.realpath(filepath),
                                     os.path.realpath(pkgdirpath))
            os.symlink(source, pkgpath)


if __name__ == '__main__':
    main()
